### ISSUE TITLE
Исправить ошибку в методе трапеций (класс TrapezoidTask): "При вводе четного количества точек или единицы программа находит неправильное решение сгенерированного задания"

### ISSUE THREAD

**Issue by sergeyyurev** [moevm/mse_functions_interpolation_and_numerical_integration_tasks#91]
"При вводе четного количества точек или единицы программа находит неправильное решение сгенерированного задания"

(Было установлено, что ошибка происходит на этапе генерации задания)

**Comment by Fikafusik** [comment]
[Дублирует](https://github.com/moevm/mse_functions_interpolation_and_numerical_integration_tasks/issues/88)
